title: My awesome title
author: Brennnesel
date: 2020-11-20
email: bro@bro.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description for my new site. You can edit this
  line in _config.yml.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
